name: globbing
version: 1.0.0
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Globbing is a library for pattern matching based on wildcard characters.
homepage: https://github.com/mezoni/globbing
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  path: '^1.8.0'
dev_dependencies:  
  pedantic: ^1.8.0
  test: any
